#PBS -N wildtype7
#PBS -l nodes=1:ppn=10
#PBS -l mem=2GB
#PBS -l file=100MB
#PBS -M hvu@colgate.edu
#PBS -q biomath
#PBS -j oe
#PBS -o output.pbs-job7
#PBS -l walltime=480:00:00
cd $PBS_O_WORKDIR

time mpirun -np 5 ~/segmentationClock2016/sres/sres -p 20 -r ~/segmentationClock/sres/ranges.txt -f ~/segmentationClock2016/stochastic/stochastic -t ~/segmentationClock2016/sres/output/wt7.txt -G 0 > wildtype7.txt

